### ISSUE TITLE
Library is currently hardwired for Wire

### ISSUE THREAD

**Issue by PaulZC** [sparkfun/SparkFun_MPL3115A2_Breakout_Arduino_Library#4]
Hi @nseidle / all,
This is an old library, but the [MPL3115A2 altitude/pressor sensor](https://www.sparkfun.com/products/11084) is still available and is still a useful sensor.
I tried to connect one to the SCL1/SDA1 pins on the [Artemis Thing Plus](https://www.sparkfun.com/products/15574) but found that the library was hardwired for Wire and couldn't get it to connect on the alternate I2C (TwoWire) port(s).
So, I've submitted a pull request ( #3 ) that corrects this. The .begin will still default to Wire, but you can now point it at the alternate TwoWire ports as well. I've also included an example showing how to connect to SCL1/SDA1 on the Thing Plus. I also did a bit of tidying-up and put the register definitions into an enum.
The examples could really do with a full make-over as they don't conform to the new numbering scheme and [one of the examples](https://github.com/sparkfun/SparkFun_MPL3115A2_Breakout_Arduino_Library/tree/master/examples/SparkFunPressure) seems to contain a full copy of the library (which also needs updating). But life is short!
Enjoy!
_**Paul**_

**Comment by nseidle** [comment]
Yep. An oldie but a goodie. Thank you for the updates.

Agreed - The examples need to be redone to conform to our new graduated structure. I'll open a separate issue for that. In the mean time, I'll roll in your changes.
